# Introduction to NumPy

## Exercises:

### 1. Update/Upgrade the NumPy package to the latest version

In [3]:

pip install numpy --upgrade

Note: you may need to restart the kernel to use updated packages.


### 2. Install/Upgrade another package (e.g. Pandas) 

In [4]:
pip install pandas --upgrade

Note: you may need to restart the kernel to use updated packages.


### 3. Import NumPy as <i> np </i>

In [5]:
import numpy as np

### 4. Use the<i> np.array() </i>function to create an array variable - <i>array_hw_1</i> with the numbers 4,5,7 and 10 in it

In [6]:
array_hw_1 = np.array([4, 5, 7, 10])
print(array_hw_1)

[ 4  5  7 10]


### 5. Display the new array on screen

In [7]:
print(array_hw_1)

[ 4  5  7 10]


### 6. Create a 2x2 array with the same values as <i> array_hw_1 </i> and display it on the screen

In [8]:
array_hw_1 = np.array([4, 5, 7, 10])
array_2x2 = np.reshape(array_hw_1, (2, 2))
print(array_2x2)

[[ 4  5]
 [ 7 10]]


### 7. Call the <i> np.mean() </i> function on each array

In [9]:
array_hw_1 = np.array([4, 5, 7, 10])
array_2x2 = np.reshape(array_hw_1, (2, 2))

mean_hw_1 = np.mean(array_hw_1)
mean_2x2 = np.mean(array_2x2)

print("Mean of array_hw_1:", mean_hw_1)
print("Mean of array_2x2:", mean_2x2)

Mean of array_hw_1: 6.5
Mean of array_2x2: 6.5


### 8. Use the <i> axis </i> argument to find the mean for all the rows of <i> array_hw_2</i>

In [10]:
array_hw_1 = np.array([4, 5, 7, 10])
array_2x2 = np.reshape(array_hw_1, (2, 2))

# Calculate the mean for each row
mean_rows_2x2 = np.mean(array_2x2, axis=1)

print("Mean for each row of array_2x2:", mean_rows_2x2)

Mean for each row of array_2x2: [4.5 8.5]


### 9. Use the <i>axis</i> argument to find the mean for all the columns of <i>array_hw_2</i>

In [11]:
array_hw_1 = np.array([4, 5, 7, 10])
array_hw_2 = np.reshape(array_hw_1, (2, 2))

# Calculate the mean for each column
mean_columns_2x2 = np.mean(array_hw_2, axis=0)

print("Mean for each column of array_hw_2:", mean_columns_2x2)

Mean for each column of array_hw_2: [5.5 7.5]


### 10. Use the <i> Shift + Tab </i> shorcut on <i> np.mean() </i> to check what possible arguments we can specify. 

### 11. Set the <i> dtype </i> argument equal to <i> np.int </i> and compare the results 

In [13]:
array_hw_1 = np.array([4, 5, 7, 10])
array_hw_2 = np.reshape(array_hw_1, (2, 2))

# Calculate the mean for each column with dtype=int
mean_columns_2x2_int = np.mean(array_hw_2, axis=0, dtype=int)

print("Mean for each column of array_hw_2 with dtype=int:", mean_columns_2x2_int)

Mean for each column of array_hw_2 with dtype=int: [5 7]
